[project]
name = "sharats-me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pelican-sitemap>=1.2.0",
    "pelican[markdown]>=4.11.0",
    "pygments>=2.18.0",
    "requests>=2.32.3",
]
