on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run:
          sed 's/ /_version=/' .tool-versions | tee -a "$GITHUB_OUTPUT"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.versions.outputs.python_version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: pelican --ignore-cache --fatal errors

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy output --project-name=sharats-me
