name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get versions
        id: versions
        run:
          echo "python_version=$(cat .python-version)" | tee -a "$GITHUB_OUTPUT"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.versions.outputs.python_version }}

      - name: Build
        env:
          PYTHONPATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget 'https://github.com/go-task/task/releases/download/v3.44.0/task_linux_amd64.tar.gz'
          tar -xzf task_linux_amd64.tar.gz task
          ./task build

      - name: Publish
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify --telemetry-disable
          netlify deploy --prod --site sharats-me --dir output
