on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run:
          sed 's/ /_version=/' .tool-versions | tee -a "$GITHUB_OUTPUT"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.versions.outputs.python_version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          wget 'https://github.com/go-task/task/releases/download/v3.28.0/task_linux_amd64.tar.gz'
          tar -xzf task_linux_amd64.tar.gz task
          ./task build-ci

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Publish
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify --telemetry-disable
          netlify deploy --prod --site sharats-me --dir output
